# Generated by Django 3.0.7 on 2020-06-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=100)),
                ('issue_level', models.IntegerField()),
                ('issue_description', models.CharField(max_length=100)),
                ('issue_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Project')),
            ],
        ),
    ]
