# Generated by Django 3.0.7 on 2020-06-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_project_project_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
